/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.RSA.Board;

import com.RSA.File.Statistics;
import com.RSA.Computer.AI;
import com.RSA.Help.AboutMe;
import com.RSA.Help.Instruction;
import com.RSA.Result.ResultSheet;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Sabuz
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
       private AI computerMove;
       private ResultSheet score;
       private ArrayList<NextMove> nxtmv;
       
       private int move[];
       private int depth;
       
       private boolean GameType;
    
    public MainFrame() {
        super("Tic Tac Toe");
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        game_Initialize();
        GameType = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn00 = new javax.swing.JButton();
        Btn01 = new javax.swing.JButton();
        Btn02 = new javax.swing.JButton();
        Btn11 = new javax.swing.JButton();
        Btn10 = new javax.swing.JButton();
        Btn12 = new javax.swing.JButton();
        Btn20 = new javax.swing.JButton();
        Btn21 = new javax.swing.JButton();
        Btn22 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuGameType = new javax.swing.JMenu();
        itemComputer = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemHuman = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemUndo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemStatistics = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        itemInstruction = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        Btn00.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn00ActionPerformed(evt);
            }
        });

        Btn01.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn01ActionPerformed(evt);
            }
        });

        Btn02.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn02ActionPerformed(evt);
            }
        });

        Btn11.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn11ActionPerformed(evt);
            }
        });

        Btn10.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn10ActionPerformed(evt);
            }
        });

        Btn12.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn12ActionPerformed(evt);
            }
        });

        Btn20.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn20ActionPerformed(evt);
            }
        });

        Btn21.setFont(new java.awt.Font("Constantia", 0, 11)); // NOI18N
        Btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn21ActionPerformed(evt);
            }
        });

        Btn22.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N

        menuGameType.setText("New Game");
        menuGameType.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N

        itemComputer.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemComputer.setText("Against Computer");
        itemComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComputerActionPerformed(evt);
            }
        });
        menuGameType.add(itemComputer);
        menuGameType.add(jSeparator4);

        itemHuman.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemHuman.setText("Against Human");
        itemHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHumanActionPerformed(evt);
            }
        });
        menuGameType.add(itemHuman);

        menuFile.add(menuGameType);
        menuFile.add(jSeparator1);

        itemUndo.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemUndo.setText("Undo");
        itemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUndoActionPerformed(evt);
            }
        });
        menuFile.add(itemUndo);
        menuFile.add(jSeparator2);

        itemStatistics.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemStatistics.setText("Statistics");
        itemStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStatisticsActionPerformed(evt);
            }
        });
        menuFile.add(itemStatistics);
        menuFile.add(jSeparator3);

        itemExit.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        menuFile.add(itemExit);

        jMenuBar1.add(menuFile);

        menuHelp.setText("Help");
        menuHelp.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N

        itemInstruction.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemInstruction.setText("Instruction");
        itemInstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstructionActionPerformed(evt);
            }
        });
        menuHelp.add(itemInstruction);
        menuHelp.add(jSeparator5);

        itemAbout.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        itemAbout.setText("About Me");
        itemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(itemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void game_Initialize()
    {
        computerMove = new AI();
        move = new int[5];
        score = new ResultSheet();
        nxtmv = new ArrayList<NextMove>();
        depth = 9;
        setNull();
    }
    
    private void setNull()
    {
        Btn00.setText(null);
        Btn00.setEnabled(true);
        
        Btn01.setText(null);
        Btn01.setEnabled(true);
        
        Btn02.setText(null);
        Btn02.setEnabled(true);
        
        Btn10.setText(null);
        Btn10.setEnabled(true);
        
        Btn11.setText(null);
        Btn11.setEnabled(true);
        
        Btn12.setText(null);
        Btn12.setEnabled(true);
        
        Btn20.setText(null);
        Btn20.setEnabled(true);
        
        Btn21.setText(null);
        Btn21.setEnabled(true);
        
        Btn22.setText(null);
        Btn22.setEnabled(true);
        
    }
    
    
    private void itemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutActionPerformed
        new AboutMe(this, false).setVisible(true);
    }//GEN-LAST:event_itemAboutActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    
    private boolean setPlayerMove(JButton btn, int x, int y, String str)
    {
        btn.setText(str);
        btn.setEnabled(false);
        computerMove.setPlayer(str.charAt(0), x, y);
        depth = depth - 1;
        
        NextMove mv = new NextMove();
        mv.setRow(x);
        mv.setColumn(y);
        nxtmv.add(mv);
        
       return computerMove.isWin(str.charAt(0));
        
    }
    
    private boolean setComputerMove()
    {
        move = computerMove.minmax(depth, 'O', -200, 200);
        computerMove.setPlayer('O', move[1], move[2]);
        setBoard(move[1], move[2], false, "0");
        depth = depth - 1;
        
        NextMove mv = new NextMove();
        mv.setRow(move[1]);
        mv.setColumn(move[2]);
        nxtmv.add(mv);
        
        return computerMove.isWin('O');
    }
    
    private void setBoard(int r, int c, boolean check, String text)
    {
        if(r == 0 && c == 0)
        {
            Btn00.setEnabled(check);
            Btn00.setText(text);
        }
        else if(r == 0 && c == 1)
        {
            Btn01.setEnabled(check);
            Btn01.setText(text);
        }
        else if(r == 0 && c == 2)
        {
            Btn02.setEnabled(check);
            Btn02.setText(text);
        }
        else if(r == 1 && c == 0)
        {
            Btn10.setEnabled(check);
            Btn10.setText(text);
        }
            
        else if(r == 1 && c == 1)
        {
            Btn11.setEnabled(check);
            Btn11.setText(text);
        }
        else if(r == 1 && c == 2)
        {
            Btn12.setEnabled(check);
            Btn12.setText(text);
        }
        else if(r == 2 && c == 0)
        {
            Btn20.setEnabled(check);
            Btn20.setText(text);
        }
        else if(r == 2 && c == 1)
        {
            Btn21.setEnabled(check);
            Btn21.setText(text);
        }
        else if(r == 2 && c == 2)
        {
            Btn22.setEnabled(check);
            Btn22.setText(text);
        }
        else
            return;
        
    }
    
    private void setWinMessage(String Message)
    {
        JOptionPane.showMessageDialog(null, Message, "Result", JOptionPane.INFORMATION_MESSAGE);
        game_Initialize();
    }
            
    
    private void move(JButton btn, int r, int c)
    {
        if(GameType == false)
         {
             if(setPlayerMove(btn, r, c, "X") == true)
             {    
                 setWinMessage("You win the game.");
                 score.updateResult(0);
                 return;
             }
             else if(depth == 0)
             {
                 setWinMessage("Match Drawn.");
                 score.updateResult(1);
                 return;
             }
         
             if(setComputerMove() == true)
             {
                 setWinMessage("Computer win the game.");
                 score.updateResult(2);
                 return;
             }
         }
        
         else if(depth % 2 == 1)
         {
             if(setPlayerMove(btn, r, c, "X") == true)
             {
                 setWinMessage("Player 1 win the game.");
                 score.updateResult(0);
                 return;
             }
             else if(depth == 0)
             {
                 setWinMessage("Match Drawn.");
                 score.updateResult(1);
                 return;
             }
         }
         else
         {
             if(setPlayerMove(btn, r, c, "O") == true)
             {
                 setWinMessage("Player 2 win the game.");
                 score.updateResult(2);
                 return;
                         
             }
         }
        
    }
    
    private void Btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn00ActionPerformed
         move(Btn00, 0, 0);
    }//GEN-LAST:event_Btn00ActionPerformed

    private void Btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn01ActionPerformed
        move(Btn01, 0, 1);
    }//GEN-LAST:event_Btn01ActionPerformed

    private void Btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn02ActionPerformed
        move(Btn02, 0, 2);
    }//GEN-LAST:event_Btn02ActionPerformed

    private void Btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn10ActionPerformed
        move(Btn10, 1, 0);
    }//GEN-LAST:event_Btn10ActionPerformed

    private void Btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn11ActionPerformed
        move(Btn11, 1, 1);
    }//GEN-LAST:event_Btn11ActionPerformed

    private void Btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn12ActionPerformed
        move(Btn12, 1, 2);
    }//GEN-LAST:event_Btn12ActionPerformed

    private void Btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn20ActionPerformed
        move(Btn20, 2, 0);
    }//GEN-LAST:event_Btn20ActionPerformed

    private void Btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn21ActionPerformed
        move(Btn21, 2, 1);
    }//GEN-LAST:event_Btn21ActionPerformed

    private void Btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn22ActionPerformed
        move(Btn22, 2, 2);
    }//GEN-LAST:event_Btn22ActionPerformed

    private void itemComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComputerActionPerformed
        GameType = false;
    }//GEN-LAST:event_itemComputerActionPerformed

    private void itemHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHumanActionPerformed
        GameType = true;
    }//GEN-LAST:event_itemHumanActionPerformed

    private void itemStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStatisticsActionPerformed
        new Statistics(this, true).setVisible(true);
    }//GEN-LAST:event_itemStatisticsActionPerformed

    private void itemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUndoActionPerformed
        int r,c;
        
        
        if(nxtmv.size() > 1)
        {
            r = nxtmv.get(nxtmv.size() - 1).getRow();
            c = nxtmv.get(nxtmv.size() - 1).getColumn();
        
            computerMove.setPlayer('B', r, c);
            setBoard(r, c, true, null);
            nxtmv.remove(nxtmv.size() - 1);
            depth = depth + 1;
        
            r = nxtmv.get(nxtmv.size() - 1).getRow();
            c = nxtmv.get(nxtmv.size() - 1).getColumn();
        
            computerMove.setPlayer('B', r, c);
            setBoard(r, c, true, null);
            nxtmv.remove(nxtmv.size() - 1);
            depth = depth + 1;
        }
        
    }//GEN-LAST:event_itemUndoActionPerformed

    private void itemInstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstructionActionPerformed
        new Instruction(this, true).setVisible(true);
    }//GEN-LAST:event_itemInstructionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn00;
    private javax.swing.JButton Btn01;
    private javax.swing.JButton Btn02;
    private javax.swing.JButton Btn10;
    private javax.swing.JButton Btn11;
    private javax.swing.JButton Btn12;
    private javax.swing.JButton Btn20;
    private javax.swing.JButton Btn21;
    private javax.swing.JButton Btn22;
    private javax.swing.JMenuItem itemAbout;
    private javax.swing.JMenuItem itemComputer;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemHuman;
    private javax.swing.JMenuItem itemInstruction;
    private javax.swing.JMenuItem itemStatistics;
    private javax.swing.JMenuItem itemUndo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuGameType;
    private javax.swing.JMenu menuHelp;
    // End of variables declaration//GEN-END:variables
}
